In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_excel("data_uts_sk5222_9Maret2023.xlsx")
data

Nama  Gender  Jenis Pembayaran  Banyaknya belanja  Biaya  Penghasilan  \
0   Andi         1                 1                  3    100      5000000   
1   Budi         1                 0                  1     50      2000000   
2   Cici         0                 1                  2     80      3000000   
3   Dedi         1                 0                  1     30      1500000   
4   Euis         0                 1                  3     90      3500000   
5   Farhan       1                 0                  2     60      2500000   
6   Gina         0                 1                  3    100      4000000   
7   Hasan        1                 1                  1     30      1000000   
8   Indah        0                 0                  2     80      3000000   
9   Joko         1                 1                  1     40      1500000   
10  Kiki         0                 0                  2     70      2500000   
11  Lina         0                 1                  3    120      4500000   
12  Maman        1                 0                  2     60      2000000   
13  Nana         0                 1                  3     80      3500000   
14  Oki          1                 0                  1     20      1000000   
15  Putri        0                 1                  2     70      2500000   
16  Qonita       0                 1                  3    100      4000000   
17  Rizal        1                 0                  1     40      1500000   
18  Sari         0                 1                  2     60      2000000   
19  Taufik       1                 1                  3     90      3500000   

    Bonus  
0       0  
1       0  
2       1  
3       0  
4       1  
5       0  
6       1  
7       0  
8       0  
9       0  
10      0  
11      1  
12      0  
13      1  
14      0  
15      0  
16      1  
17      0  
18      0  
19      1

#1. Remove the label 'Bonus' dan 'Nama'


In [37]:
data=data.drop(['Nama'],axis=1)

In [38]:
df_1=data.drop(['Bonus'], axis=1)
df_1

Gender  Jenis Pembayaran  Banyaknya belanja  Biaya  Penghasilan
0        1                 1                  3    100      5000000
1        1                 0                  1     50      2000000
2        0                 1                  2     80      3000000
3        1                 0                  1     30      1500000
4        0                 1                  3     90      3500000
5        1                 0                  2     60      2500000
6        0                 1                  3    100      4000000
7        1                 1                  1     30      1000000
8        0                 0                  2     80      3000000
9        1                 1                  1     40      1500000
10       0                 0                  2     70      2500000
11       0                 1                  3    120      4500000
12       1                 0                  2     60      2000000
13       0                 1                  3     80      3500000
14       1                 0                  1     20      1000000
15       0                 1                  2     70      2500000
16       0                 1                  3    100      4000000
17       1                 0                  1     40      1500000
18       0                 1                  2     60      2000000
19       1                 1                  3     90      3500000

#2. Prepocessing the Data

In [5]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
print("Standardizing")
df_2 = standard_scaler.fit_transform(df_1)

Standardizing


In [6]:
df_2 = pd.DataFrame(df_2, columns=['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan'])
df_2

Gender  Jenis Pembayaran  Banyaknya belanja     Biaya  Penghasilan
0      1.0          0.816497           1.180603  1.171700     2.028973
1      1.0         -1.224745          -1.304877 -0.688141    -0.617514
2     -1.0          0.816497          -0.062137  0.427764     0.264649
3      1.0         -1.224745          -1.304877 -1.432078    -1.058595
4     -1.0          0.816497           1.180603  0.799732     0.705730
5      1.0         -1.224745          -0.062137 -0.316173    -0.176432
6     -1.0          0.816497           1.180603  1.171700     1.146811
7      1.0          0.816497          -1.304877 -1.432078    -1.499676
8     -1.0         -1.224745          -0.062137  0.427764     0.264649
9      1.0          0.816497          -1.304877 -1.060110    -1.058595
10    -1.0         -1.224745          -0.062137  0.055795    -0.176432
11    -1.0          0.816497           1.180603  1.915637     1.587892
12     1.0         -1.224745          -0.062137 -0.316173    -0.617514
13    -1.0          0.816497           1.180603  0.427764     0.705730
14     1.0         -1.224745          -1.304877 -1.804046    -1.499676
15    -1.0          0.816497          -0.062137  0.055795    -0.176432
16    -1.0          0.816497           1.180603  1.171700     1.146811
17     1.0         -1.224745          -1.304877 -1.060110    -1.058595
18    -1.0          0.816497          -0.062137 -0.316173    -0.617514
19     1.0          0.816497           1.180603  0.799732     0.705730

#3. Use three different initial centroid values 

In [7]:
np.random.seed(42)
init_1 = np.random.rand(2,5)
print('Initial centroids of model 1: \n', init_1)
init_2 = np.random.rand(2,5)
print('Initial centroids of model 2: \n', init_2)
init_3 = np.random.rand(2,5)
print('Initial centroids of model 3: \n', init_3)

Initial centroids of model 1: 
 [[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]]
Initial centroids of model 2: 
 [[0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]
Initial centroids of model 3: 
 [[0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]]


#4. Compare between the three model

In [8]:
from sklearn.cluster import KMeans
model_1 = KMeans(n_clusters=2, init=init_1, n_init=1).fit(df_2)
model_2 = KMeans(n_clusters=2, init=init_2, n_init=1).fit(df_2)
model_3 = KMeans(n_clusters=2, init=init_3, n_init=1).fit(df_2)


In [9]:
y_predicted_1 = model_1.fit_predict(df_2[['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan']])
y_predicted_1
 
df_1['Bonus'] = y_predicted_1

In [10]:
y_predicted_1

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1],
      dtype=int32)

In [11]:
T = pd.read_excel("data_uts_sk5222_9Maret2023.xlsx")['Bonus']

In [12]:
from sklearn.metrics import accuracy_score
accuracy_score(T, model_1.labels_)

0.75

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(T, model_1.labels_)

array([[8, 5],
       [0, 7]])

In [14]:
y_predicted_2 = model_2.fit_predict(df_2[['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan']])
y_predicted_2
 
df_1['Bonus'] = y_predicted_2

In [15]:
y_predicted_2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
      dtype=int32)

In [16]:
from sklearn.metrics import accuracy_score
accuracy_score(T, model_2.labels_)

0.2

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(T, model_2.labels_)

array([[4, 9],
       [7, 0]])

In [18]:
y_predicted_3 = model_3.fit_predict(df_2[['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan']])
y_predicted_3
 
df_1['Bonus'] = y_predicted_3

In [19]:
y_predicted_3

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1],
      dtype=int32)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(T, model_3.labels_)

0.8

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(T, model_3.labels_)

array([[9, 4],
       [0, 7]])

#5. Compare with result from UTS (Decision Tree and ANN)

In [35]:
#Learning Model using Decision Tree 
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [77]:
X =data.iloc[:, :5]
y = data["Bonus"]

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [73]:
dt = tree.DecisionTreeClassifier()

In [74]:
clf = dt.fit(X_train, y_train)

In [75]:
y_pred =dt.predict(X_train)

In [76]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_train, y_pred)
print(cm)
accuracy_score(y_train,y_pred)

[[11  0]
 [ 0  5]]


1.0

In [59]:
#Using ANN Model
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [60]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [61]:
model = MLPClassifier(hidden_layer_sizes=(3, 4), max_iter=2, random_state=42)

In [62]:
model.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (2) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(3, 4), max_iter=2, random_state=42)

In [63]:
y_pred = model.predict(X_test)

In [64]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.25


#6. Bisecting K-Means algorithm and compare with the result from K-Means, Decision tree, and ANN

In [22]:
from sklearn.cluster import BisectingKMeans
model_4 = BisectingKMeans(n_clusters=2, n_init=1).fit(df_2)
model_5 = BisectingKMeans(n_clusters=2, n_init=1).fit(df_2)
model_6 = BisectingKMeans(n_clusters=2, n_init=1).fit(df_2)

In [23]:
y_predicted_4 = model_4.fit_predict(df_2[['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan']])
y_predicted_4
 
df_1['Bonus'] = y_predicted_4

In [24]:
y_predicted_4

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1],
      dtype=int32)

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(T, model_4.labels_)

0.75

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(T, model_4.labels_)

array([[8, 5],
       [0, 7]])

In [27]:
y_predicted_5 = model_5.fit_predict(df_2[['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan']])
y_predicted_5
 
df_1['Bonus'] = y_predicted_5

In [28]:
y_predicted_5

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
      dtype=int32)

In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(T, model_5.labels_)

0.2

In [30]:
from sklearn.metrics import confusion_matrix
confusion_matrix(T, model_5.labels_)

array([[4, 9],
       [7, 0]])

In [31]:
y_predicted_6 = model_6.fit_predict(df_2[['Gender','Jenis Pembayaran','Banyaknya belanja','Biaya','Penghasilan']])
y_predicted_6
 
df_1['Bonus'] = y_predicted_6

In [32]:
y_predicted_6

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1],
      dtype=int32)

In [33]:
from sklearn.metrics import accuracy_score
accuracy_score(T, model_6.labels_)

0.75

In [34]:
from sklearn.metrics import confusion_matrix
confusion_matrix(T, model_6.labels_)

array([[8, 5],
       [0, 7]])